service: mst

provider:
  name: aws
  runtime: python3.7

  stage: funsies

package:
  individually: true
  exclude:
    - lambda_functions/**
    - node_modules/**
    - venv/**
    - pylintrc
    - "*.json"
    - README.md
    - requirements.txt
    - .gitignore
    - appsync/**
    - tests/**

functions: ${file(config/functions.yml)}
resources: ${file(config/resources.yml)}

plugins:
  - serverless-pseudo-parameters

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true